### ISSUE TITLE
Cannot start on v5.1.114+

### ISSUE THREAD

**Issue by drizzt** [linuxserver/docker-synclounge#11]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
It should start

## Current Behavior
It returns a node.js error and exits

## Steps to Reproduce
docker run -ti --rm lscr.io/linuxserver/synclounge:latest

## Environment
**OS:** Irrilevant, it's a problem of the upstream code
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

## Docker logs

Starting from v5.1.114 it's not possible to start the code since upstream uses, and it's a really bad practice, an auto-merge github workflow in order to merge automatically any update on the libraries, but this means it may breaks if the new update is not backward compatible (and this is the case).

I suggest to **remove** all the builds starting from v5.1.114 until upstream really fixes the issues https://github.com/synclounge/synclounge/issues/1035, https://github.com/synclounge/synclounge/issues/1041

I already did the git bisection, so I'm ready to tell upstream what's exactly broken and how to fix it, but in the meanwhile they merge it please remove the broken builds

**Comment by Roxedus** [comment]
We will not remove builds, we can consider stopping new builds.

**Comment by aptalca** [comment]
It's broken at head. We can't make it work. Asked upstream for help a while back but haven't received it yet.

To be frank, I'm considering deprecating this image as usage seems to have waned since plex built in similar functionality and there's been very minimal activity upstream (almost all activity is dependabot PRs).

**Comment by drizzt** [comment]
I send a PR in order to fix it https://github.com/synclounge/syncloungeserver/pull/617 hopefully they'll apply it...
I know Plex has a similar feature built-in, but if you want to play the same video on multiple Plex with the same account you must use something like Synclounge, since the Plex built-in feature doesn't work for this

**Comment by aptalca** [comment]
@drizzt they merged upstream and our image is now working again. Thanks so much
