### ISSUE TITLE
Request: Customizable server list

### ISSUE THREAD

**Issue by Apuru** [linuxserver/docker-synclounge#3]
Some completely not necessary but nice QoL features to have with this package. I know that this LSIO images are supposed to be fast to deploy but it would be nice to have these customization features.

1. Add a volume for a path-to-config then add the server object file to the config folder so we can edit our server list for fun/customization.

2. Add a secondary server list that can be renamed to replace the default server list. The second list includes all the default synclounge servers and space for 1 custom server. This helps when a default server is closer to a viewer and could be used instead of the custom server.

(Starbix' package by default adds all the default servers and leaves space for 1 custom server which I really like https://hub.docker.com/r/starbix/synclounge it also accepts the custom_server env variable which is my 3rd suggestion)

Current: https://i.imgur.com/RyVowlw.png
What I would prefer: https://i.imgur.com/hMWeoq9.png

3. Accept the custom_server env variable to either add or replace the LSIO Server.  
Edit: It looks like this would work with customserver={object}, havent tested it yet though.

**Comment by aptalca** [comment]
The purpose of this image is to provide a server web app combo for personal home use that is dead simple to set up. I honestly don't know why people (other than the hosted official synclounge servers) would want multiple servers listed as each server can already host many separate rooms. You really only need one server.

In any case, the server info is hosted in this file: https://github.com/linuxserver/docker-synclounge/blob/master/root/defaults/servers.json

You can create your own custom servers.json file and volume map it in as `-v /path/to/custom.json:/defaults/servers.json`

**Comment by Apuru** [comment]
Thanks for this! This is exactly what I needed.
